### ISSUE TITLE
change db 

### ISSUE THREAD

**Issue by yoni536** [ardalis/CleanArchitecture.WorkerService#10]
how can I update the db to use DynamoDB (aws)
dynamodb info:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CRUDHighLevelExample1.html
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NET.html
https://www.youtube.com/watch?v=B190tcu1ERk
http://cdn.cdata.com/help/DDE/ado/pg_usingEFCoreIntro.htm

**Comment by yoni536** [comment]
how can I update the db to use DynamoDB (aws)
dynamodb info: 
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CRUDHighLevelExample1.html
- https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NET.html
- https://www.youtube.com/watch?v=B190tcu1ERk

**Comment by ardalis** [comment]
Not planned.
